FROM ubuntu:24.04
#install dotnet sdk and dependetes to create aot builds
RUN sudo add-apt-repository -y ppa:dotnet/backports && sudo apt-get update && sudo apt-get install -y dotnet-sdk-9.0 ca-certificates && rm -rf /var/lib/apt/lists/*
#add dotnet tools to path
ENV PATH="$PATH:/root/.dotnet/tools"
#enter in shell
CMD ["/bin/sh"]